version: '3.9'

services:
  postgres:
    image: postgres:15-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bikbulat
      POSTGRES_PASSWORD: bikbulat
      POSTGRES_DB: character_ai

  chatbot:
    image: python-bot:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ~/apps/python_bot:/app
    links:
      - postgres